get:
    tags:
        - movies
    responses:
        '200':
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        Game with details:
                            value:
                                id: 1
                                name: Harry Potter and the Philosopher's Stone
                                description: movie
                                year: 2001
            description: returns details of a movie by its id
        '400':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/error'
                    examples:
                        Missing id:
                            value: '{''Error'': ''invalid movie id''}'
            description: ID was missing
        '404':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/error'
                    examples:
                        Missing movie:
                            value:
                                Error: Movie not found
            description: Movie was not found in array of movies
    operationId: id
    summary: Get full details of a Game
    description: Return dull details of a given movie based on the id
delete:
    tags:
        - movies
    parameters:
        -
            examples:
                example id:
                    value: '1'
            name: id
            description: ID of the movie
            schema:
                type: integer
            in: path
            required: true
    responses:
        '204':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/error'
                    examples:
                        example of a deleted movie:
                            value:
                                -
                                    error: no content
            description: Return status 404 to the user if deletion of the movie has been succesful
        '404':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/error'
                    examples:
                        Missing movie:
                            value:
                                -
                                    error: movie was not found
            description: 'Return status code 404 to the user, if movie with this id does not exist'
    operationId: id
    summary: Delete a movie
    description: Delete the movie by id
parameters:
    -
        examples:
            example id:
                value: '{1}'
        name: id
        description: ID of the movie
        schema:
            type: integer
        in: path
        required: true
