description: ''
get:
    tags:
        - movies
    responses:
        '200':
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        List of movies:
                            value:
                                - 'Harry Potter '
                                - The game of thrones
            description: Returns a list of movies
    summary: Get a list of all movies
    description: Returns a list of all games in API
post:
    requestBody:
        content:
            application/json:
                schema:
                    $ref: '#/components/schemas/Movie'
                examples:
                    Added Movie:
                        value:
                            name: Harry Potter and the Philosopher's Stone
                            description: movie
                            year: '2001'
        required: true
    tags:
        - movies
    responses:
        '201':
            content:
                application/json:
                    schema:
                        $ref: '#/components/schemas/Movie'
                    examples:
                        Created Movie:
                            value:
                                id: 1
                                name: Harry Potter and the Philosopher's Stone
                                description: movie
                                year: 2001
            description: Added Movie
    summary: Add a new Movie
    description: 'Retrns the created Movie to the user, if creation is succesful'
